CyclomaticComplexity:
  Max: 5

AllCops:
  Include:
    - '**/*.rb'
    - rakelib/*.rake
    - 'Gemfile'
    - 'Rakefile'
    - 'reveal-ck.gemspec'
    - 'files/reveal-ck/Guardfile'
  Exclude:
    - tmp/**/*
    - files/reveal.js/**/*

FileName:
  Exclude:
    - Gemfile
    - reveal-ck.gemspec
    - lib/reveal-ck.rb
    - files/reveal-ck/Guardfile

Metrics/BlockLength:
  Exclude:
    - bin/reveal-ck
    - reveal-ck.gemspec
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - lib/reveal-ck/config.rb
    - lib/reveal-ck/builders/create_index_html.rb
